import type { BusRoute } from '@/lib/types';

export const busRoutes: BusRoute[] = [
  { id: 'bus-1', operator: 'BharatStay Travels', fromCity: 'Mumbai', toCity: 'Pune', departureTime: '22:00', arrivalTime: '01:30', durationMinutes: 210, busType: 'Volvo AC Sleeper', isAc: true, seatType: 'Sleeper', amenities: ['Blanket', 'Water Bottle', 'Charging Point'], rating: 4.3, seatsAvailable: 18, price: 899 },
  { id: 'bus-2', operator: 'Rajasthan Roadways Premium', fromCity: 'Delhi', toCity: 'Jaipur', departureTime: '07:00', arrivalTime: '12:00', durationMinutes: 300, busType: 'AC Seater', isAc: true, seatType: 'Seater', amenities: ['Wi-Fi', 'Charging Point'], rating: 4.0, seatsAvailable: 24, price: 649 },
  { id: 'bus-3', operator: 'SouthStar Travels', fromCity: 'Bengaluru', toCity: 'Chennai', departureTime: '23:30', arrivalTime: '05:30', durationMinutes: 360, busType: 'Non-AC Sleeper', isAc: false, seatType: 'Sleeper', amenities: ['Water Bottle'], rating: 3.8, seatsAvailable: 12, price: 549 },
  { id: 'bus-4', operator: 'Himgiri Express', fromCity: 'Delhi', toCity: 'Manali', departureTime: '18:00', arrivalTime: '08:00', durationMinutes: 840, busType: 'Volvo AC Sleeper', isAc: true, seatType: 'Sleeper', amenities: ['Blanket', 'Charging Point', 'Movie'], rating: 4.5, seatsAvailable: 9, price: 1499 },
  { id: 'bus-5', operator: 'Kaveri Travels', fromCity: 'Hyderabad', toCity: 'Bengaluru', departureTime: '21:15', arrivalTime: '05:45', durationMinutes: 510, busType: 'AC Sleeper', isAc: true, seatType: 'Sleeper', amenities: ['Blanket', 'Water Bottle'], rating: 4.1, seatsAvailable: 15, price: 999 },
  { id: 'bus-6', operator: 'Konkan Coastal Travels', fromCity: 'Mumbai', toCity: 'Goa', departureTime: '20:30', arrivalTime: '07:00', durationMinutes: 630, busType: 'Volvo AC Sleeper', isAc: true, seatType: 'Sleeper', amenities: ['Blanket', 'Charging Point', 'Water Bottle'], rating: 4.4, seatsAvailable: 11, price: 1299 },
  { id: 'bus-7', operator: 'Ganga Yatra Travels', fromCity: 'Delhi', toCity: 'Rishikesh', departureTime: '23:00', arrivalTime: '06:00', durationMinutes: 420, busType: 'AC Seater', isAc: true, seatType: 'Seater', amenities: ['Charging Point'], rating: 3.9, seatsAvailable: 20, price: 749 },
  { id: 'bus-8', operator: 'Nilgiri Express Travels', fromCity: 'Chennai', toCity: 'Coimbatore', departureTime: '22:45', arrivalTime: '05:15', durationMinutes: 390, busType: 'Non-AC Seater', isAc: false, seatType: 'Seater', amenities: ['Water Bottle'], rating: 3.7, seatsAvailable: 28, price: 449 },
  { id: 'bus-9', operator: 'Malabar Travels', fromCity: 'Kochi', toCity: 'Munnar', departureTime: '08:30', arrivalTime: '12:30', durationMinutes: 240, busType: 'AC Seater', isAc: true, seatType: 'Seater', amenities: ['Wi-Fi', 'Water Bottle'], rating: 4.2, seatsAvailable: 22, price: 549 },
  { id: 'bus-10', operator: 'Bengal Link Travels', fromCity: 'Kolkata', toCity: 'Digha', departureTime: '06:00', arrivalTime: '10:30', durationMinutes: 270, busType: 'AC Seater', isAc: true, seatType: 'Seater', amenities: ['Charging Point'], rating: 3.9, seatsAvailable: 17, price: 499 },
];
