import type { Flight } from '@/lib/types';

export const flights: Flight[] = [
  { id: 'fl-1', airline: 'IndiGo', airlineLogo: '🔵', flightNumber: '6E-204', fromCity: 'Mumbai', fromCode: 'BOM', toCity: 'Delhi', toCode: 'DEL', departureTime: '06:05', arrivalTime: '08:15', durationMinutes: 130, stops: 0, cabinClass: 'Economy', refundable: false, baggageKg: 15, cabinBaggageKg: 7, price: 4899 },
  { id: 'fl-2', airline: 'Air India', airlineLogo: '🔴', flightNumber: 'AI-864', fromCity: 'Delhi', fromCode: 'DEL', toCity: 'Goa', toCode: 'GOI', departureTime: '09:30', arrivalTime: '12:10', durationMinutes: 160, stops: 0, cabinClass: 'Economy', refundable: true, baggageKg: 20, cabinBaggageKg: 7, price: 6299 },
  { id: 'fl-3', airline: 'Vistara', airlineLogo: '🟣', flightNumber: 'UK-955', fromCity: 'Bengaluru', fromCode: 'BLR', toCity: 'Mumbai', toCode: 'BOM', departureTime: '14:20', arrivalTime: '16:00', durationMinutes: 100, stops: 0, cabinClass: 'Premium Economy', refundable: true, baggageKg: 20, cabinBaggageKg: 7, price: 7899 },
  { id: 'fl-4', airline: 'SpiceJet', airlineLogo: '🟠', flightNumber: 'SG-417', fromCity: 'Chennai', fromCode: 'MAA', toCity: 'Kolkata', toCode: 'CCU', departureTime: '11:45', arrivalTime: '14:05', durationMinutes: 140, stops: 0, cabinClass: 'Economy', refundable: false, baggageKg: 15, cabinBaggageKg: 7, price: 5399 },
  { id: 'fl-5', airline: 'Akasa Air', airlineLogo: '🟢', flightNumber: 'QP-1302', fromCity: 'Mumbai', fromCode: 'BOM', toCity: 'Bengaluru', toCode: 'BLR', departureTime: '18:10', arrivalTime: '19:40', durationMinutes: 90, stops: 0, cabinClass: 'Economy', refundable: false, baggageKg: 15, cabinBaggageKg: 7, price: 4599 },
  { id: 'fl-6', airline: 'IndiGo', airlineLogo: '🔵', flightNumber: '6E-6501', fromCity: 'Delhi', fromCode: 'DEL', toCity: 'Srinagar', toCode: 'SXR', departureTime: '07:15', arrivalTime: '09:05', durationMinutes: 110, stops: 0, cabinClass: 'Economy', refundable: false, baggageKg: 15, cabinBaggageKg: 7, price: 6799 },
  { id: 'fl-7', airline: 'Air India', airlineLogo: '🔴', flightNumber: 'AI-401', fromCity: 'Mumbai', fromCode: 'BOM', toCity: 'Kochi', toCode: 'COK', departureTime: '20:00', arrivalTime: '22:15', durationMinutes: 135, stops: 0, cabinClass: 'Business', refundable: true, baggageKg: 30, cabinBaggageKg: 10, price: 14999 },
  { id: 'fl-8', airline: 'Vistara', airlineLogo: '🟣', flightNumber: 'UK-772', fromCity: 'Delhi', fromCode: 'DEL', toCity: 'Leh', toCode: 'IXL', departureTime: '05:45', arrivalTime: '07:15', durationMinutes: 90, stops: 0, cabinClass: 'Economy', refundable: false, baggageKg: 15, cabinBaggageKg: 7, price: 8299 },
  { id: 'fl-9', airline: 'SpiceJet', airlineLogo: '🟠', flightNumber: 'SG-8169', fromCity: 'Kolkata', fromCode: 'CCU', toCity: 'Port Blair', toCode: 'IXZ', departureTime: '10:00', arrivalTime: '12:00', durationMinutes: 120, stops: 0, cabinClass: 'Economy', refundable: false, baggageKg: 15, cabinBaggageKg: 7, price: 7499 },
  { id: 'fl-10', airline: 'Akasa Air', airlineLogo: '🟢', flightNumber: 'QP-1719', fromCity: 'Hyderabad', fromCode: 'HYD', toCity: 'Jaipur', toCode: 'JAI', departureTime: '16:30', arrivalTime: '18:35', durationMinutes: 125, stops: 1, cabinClass: 'Economy', refundable: false, baggageKg: 15, cabinBaggageKg: 7, price: 5899 },
];
