import type { HolidayPackage } from '@/lib/types';

export const packages: HolidayPackage[] = [
  { id: 'pkg-1', title: 'Goa Beach Escape', destination: 'Goa', image: 'ocean:🏖️', nights: 3, days: 4, hotelCategory: '4-Star', mealPlan: 'Breakfast Included', transport: 'Airport transfers included', sightseeing: ['Baga Beach', 'Fort Aguada', 'Spice Plantation'], pricePerPerson: 8999 },
  { id: 'pkg-2', title: 'Kashmir Paradise Tour', destination: 'Kashmir', image: 'snow:🌸', nights: 5, days: 6, hotelCategory: '4-Star + Houseboat', mealPlan: 'All Meals Included', transport: 'Private cab + Shikara ride', sightseeing: ['Dal Lake', 'Gulmarg Gondola', 'Pahalgam Valley'], pricePerPerson: 21999 },
  { id: 'pkg-3', title: 'Kerala Backwaters', destination: 'Kerala', image: 'forest:🌴', nights: 4, days: 5, hotelCategory: '5-Star + Houseboat', mealPlan: 'Breakfast & Dinner', transport: 'AC car with driver', sightseeing: ['Alleppey Backwaters', 'Munnar Tea Gardens', 'Periyar Wildlife'], pricePerPerson: 18499 },
  { id: 'pkg-4', title: 'Manali Snow Adventure', destination: 'Manali', image: 'snow:🏔️', nights: 4, days: 5, hotelCategory: '3-Star', mealPlan: 'Breakfast Included', transport: 'Volvo + local sightseeing cab', sightseeing: ['Solang Valley', 'Rohtang Pass', 'Hidimba Temple'], pricePerPerson: 10999 },
  { id: 'pkg-5', title: 'Royal Rajasthan (Jaipur–Udaipur)', destination: 'Rajasthan', image: 'desert:🏰', nights: 6, days: 7, hotelCategory: '4-Star Heritage', mealPlan: 'Breakfast Included', transport: 'AC coach + inter-city transfers', sightseeing: ['Amber Fort', 'City Palace', 'Lake Pichola'], pricePerPerson: 16999 },
  { id: 'pkg-6', title: 'Andaman Island Hopping', destination: 'Andaman', image: 'ocean:🐠', nights: 5, days: 6, hotelCategory: '4-Star', mealPlan: 'Breakfast Included', transport: 'Ferry transfers included', sightseeing: ['Radhanagar Beach', 'Cellular Jail', 'Scuba Diving'], pricePerPerson: 26999 },
  { id: 'pkg-7', title: 'Ladakh Bike Expedition', destination: 'Ladakh', image: 'mountain:🏍️', nights: 6, days: 7, hotelCategory: 'Budget Guesthouses', mealPlan: 'Breakfast & Dinner', transport: 'Royal Enfield + support vehicle', sightseeing: ['Pangong Lake', 'Nubra Valley', 'Khardung La'], pricePerPerson: 19999 },
  { id: 'pkg-8', title: 'Honeymoon in Udaipur', destination: 'Udaipur', image: 'lake:🛶', nights: 3, days: 4, hotelCategory: '5-Star Lake View', mealPlan: 'All Meals Included', transport: 'Private airport transfers', sightseeing: ['Lake Pichola Cruise', 'Jag Mandir', 'Saheliyon Ki Bari'], pricePerPerson: 24999 },
  { id: 'pkg-9', title: 'Rishikesh Yoga & Rafting', destination: 'Rishikesh', image: 'forest:🧘', nights: 2, days: 3, hotelCategory: '3-Star Riverside Resort', mealPlan: 'Breakfast Included', transport: 'Local pickup/drop', sightseeing: ['White River Rafting', 'Laxman Jhula', 'Yoga Sessions'], pricePerPerson: 6499 },
  { id: 'pkg-10', title: 'Lonavala Monsoon Weekend', destination: 'Lonavala', image: 'forest:🌧️', nights: 2, days: 3, hotelCategory: '4-Star Resort', mealPlan: 'Breakfast Included', transport: 'Self-drive friendly', sightseeing: ['Tiger Point', 'Bhushi Dam', 'Lohagad Fort'], pricePerPerson: 5999 },
  { id: 'pkg-11', title: 'Mahabaleshwar Family Trip', destination: 'Mahabaleshwar', image: 'forest:🍓', nights: 3, days: 4, hotelCategory: '3-Star', mealPlan: 'Breakfast Included', transport: 'AC cab for sightseeing', sightseeing: ['Venna Lake', 'Strawberry Farms', 'Arthur\'s Seat'], pricePerPerson: 7499 },
  { id: 'pkg-12', title: 'Shimla–Manali Combo', destination: 'Himachal Pradesh', image: 'mountain:🚂', nights: 5, days: 6, hotelCategory: '4-Star', mealPlan: 'Breakfast Included', transport: 'AC Volvo + private cab', sightseeing: ['Mall Road', 'Kufri', 'Solang Valley'], pricePerPerson: 14999 },
];
