/**
 * Minimal Claude client for the office. Two providers:
 *  - `anthropic`: real Messages API calls (needs ANTHROPIC_API_KEY)
 *  - `stub`:      deterministic offline responses so the harness is runnable, testable
 *                 and demo-able without a key or a network
 */

const API_URL = process.env.ANTHROPIC_BASE_URL ?? 'https://api.anthropic.com';
const API_VERSION = '2023-06-01';
const RETRYABLE = new Set([408, 409, 429, 500, 502, 503, 504, 529]);

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/**
 * @typedef {{role:'user'|'assistant', content: any}} Message
 * @typedef {{model:string, system:string, messages:Message[], tools?:any[], maxTokens?:number}} CompleteInput
 * @typedef {{stopReason:string, blocks:any[], text:string, toolUses:Array<{id:string,name:string,input:any}>, usage:{input:number,output:number}}} CompleteResult
 */

function shape(body) {
	const blocks = body.content ?? [];
	return {
		stopReason: body.stop_reason ?? 'end_turn',
		blocks,
		text: blocks
			.filter((b) => b.type === 'text')
			.map((b) => b.text)
			.join('\n')
			.trim(),
		toolUses: blocks
			.filter((b) => b.type === 'tool_use')
			.map((b) => ({ id: b.id, name: b.name, input: b.input ?? {} })),
		usage: { input: body.usage?.input_tokens ?? 0, output: body.usage?.output_tokens ?? 0 },
	};
}

async function anthropicComplete(input, { retries = 4 } = {}) {
	const key = process.env.ANTHROPIC_API_KEY;
	if (!key) throw new Error('ANTHROPIC_API_KEY is not set (use OFFICE_PROVIDER=stub to run offline)');

	const payload = {
		model: input.model,
		max_tokens: input.maxTokens ?? 4000,
		system: input.system,
		messages: input.messages,
		...(input.tools?.length ? { tools: input.tools } : {}),
	};

	let lastError;
	for (let attempt = 0; attempt <= retries; attempt++) {
		try {
			const res = await fetch(`${API_URL}/v1/messages`, {
				method: 'POST',
				headers: {
					'content-type': 'application/json',
					'x-api-key': key,
					'anthropic-version': API_VERSION,
				},
				body: JSON.stringify(payload),
			});
			if (res.ok) return shape(await res.json());

			const detail = await res.text();
			if (!RETRYABLE.has(res.status)) throw new Error(`Anthropic ${res.status}: ${detail}`);
			lastError = new Error(`Anthropic ${res.status}: ${detail}`);
		} catch (error) {
			// Network faults are retryable; a non-retryable HTTP status is rethrown immediately.
			if (String(error.message).startsWith('Anthropic ') && !/\b(408|409|429|5\d\d)\b/.test(error.message)) {
				throw error;
			}
			lastError = error;
		}
		if (attempt < retries) await sleep(2 ** attempt * 1000);
	}
	throw lastError;
}

/**
 * Offline provider. Walks a scripted path through whatever tools the role was granted -
 * gather, then produce (draft / review / handoff), then summarise - so a keyless run
 * exercises the tool loop, the review gate, the handoff graph and the ledger.
 */
function stubComplete(input) {
	const turn = input.messages.filter(
		(m) => Array.isArray(m.content) && m.content.some((b) => b?.type === 'tool_result'),
	).length;
	const role = /You are the ([a-z-]+) clone/.exec(input.system)?.[1] ?? 'worker';
	const names = new Set((input.tools ?? []).map((t) => t.name));
	const call = (name, toolInput) => ({
		stopReason: 'tool_use',
		blocks: [],
		text: '',
		toolUses: [{ id: `stub_${role}_${turn}`, name, input: toolInput }],
		usage: { input: 0, output: 0 },
	});

	if (turn === 0) {
		const gather = ['read_draft', 'expiring_contracts', 'list_records', 'pricebook_lookup', 'get_record'].find(
			(n) => names.has(n),
		);
		if (gather) return call(gather, stubToolInput(gather, input));
	}

	if (turn === 1) {
		if (names.has('record_review')) {
			const file = draftPathFrom(input.messages);
			if (file) {
				return call('record_review', {
					file,
					verdict: 'revise',
					issues: ['[stub] No model reviewed this draft - offline provider.'],
				});
			}
		}
		if (names.has('save_draft')) return call('save_draft', stubToolInput('save_draft', input, role));
		if (names.has('handoff')) {
			const roster = /Colleagues: ([a-z, -]+)/.exec(JSON.stringify(input.tools ?? []))?.[1] ?? '';
			const colleague = roster
				.split(',')
				.map((s) => s.trim())
				.find((n) => n && n !== role && n !== 'reviewer');
			if (colleague) {
				return call('handoff', {
					to_role: colleague,
					task: `[stub] Follow-up delegated by ${role}.`,
					context: 'Generated by the offline stub provider.',
				});
			}
		}
	}

	const summary = {
		summary: `[stub] ${role} completed its task offline; no model call was made.`,
		findings: ['Stub provider active - set ANTHROPIC_API_KEY for real reasoning.'],
		next_actions: [],
		confidence: 'low',
	};
	return {
		stopReason: 'end_turn',
		blocks: [],
		text: '```json\n' + JSON.stringify(summary, null, 2) + '\n```',
		toolUses: [],
		usage: { input: 0, output: 0 },
	};
}

/** Pull the draft path out of a review work item's text (stub provider only). */
function draftPathFrom(messages = []) {
	for (const message of messages) {
		const text =
			typeof message.content === 'string'
				? message.content
				: (message.content ?? []).map((b) => b?.text ?? '').join('\n');
		const hit = /File: (.+\.md)\s*$/m.exec(text);
		if (hit) return hit[1].trim();
	}
	return null;
}

function stubToolInput(name, input, role = 'worker') {
	switch (name) {
		case 'list_records':
			return { collection: 'leads', limit: 3 };
		case 'get_record':
			return { collection: 'leads', id: 'lead_001' };
		case 'expiring_contracts':
			return { within_days: 75 };
		case 'pricebook_lookup':
			return { query: 'AMC' };
		case 'read_draft':
			return { file: draftPathFrom(input?.messages) ?? 'missing.md' };
		case 'save_draft':
			return {
				kind: 'note',
				title: `Stub output from ${role}`,
				body: 'Generated by the offline stub provider. No model produced this text.',
			};
		default:
			return {};
	}
}

/**
 * @param {string} provider
 * @returns {(input: CompleteInput) => Promise<CompleteResult>}
 */
export function createClient(provider) {
	if (provider === 'stub') return async (input) => stubComplete(input);
	if (provider === 'anthropic') return async (input) => await anthropicComplete(input);
	throw new Error(`Unknown provider: ${provider}`);
}
