#!/usr/bin/env node
/**
 * Regenerates CHANGELOG.md from git history.
 *
 * Generated rather than hand-written on purpose: a changelog someone has to
 * remember to update is a changelog that silently goes stale, and a stale one
 * is worse than none — it is read as fact. This reads the actual commits, so
 * it cannot disagree with what shipped.
 *
 * Usage:
 *   npm run changelog          rewrite CHANGELOG.md
 *   npm run changelog -- --check   exit 1 if it is out of date (for CI)
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = path.join(projectRoot, 'CHANGELOG.md');

/** Conventional-commit prefixes, in the order they should appear under a date. */
const SECTIONS = [
  ['feat', 'Features'],
  ['fix', 'Fixes'],
  ['perf', 'Performance'],
  ['refactor', 'Refactoring'],
  ['docs', 'Documentation'],
  ['test', 'Tests'],
  ['build', 'Build'],
  ['ci', 'CI'],
  ['chore', 'Chores'],
  ['other', 'Other'],
];

const SECTION_LABELS = new Map(SECTIONS);

function git(args) {
  return execFileSync('git', args, { cwd: projectRoot, encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 });
}

/**
 * Splits "feat(scope): subject" into its parts.
 *
 * The scope is dropped from the rendered line: every commit here is scoped to
 * this project, so "(vision-analytical)" on every entry is noise.
 */
function parseSubject(subject) {
  const match = /^(\w+)(?:\(([^)]*)\))?(!)?:\s*(.+)$/.exec(subject);
  if (!match) return { type: 'other', breaking: false, description: subject };

  const [, rawType, , bang, description] = match;
  const type = SECTION_LABELS.has(rawType) ? rawType : 'other';
  return { type, breaking: bang === '!', description };
}

function collectCommits() {
  // \x1f between fields, \x1e between records: neither appears in commit text,
  // unlike the pipes and newlines a message can legitimately contain.
  const raw = git([
    'log',
    '--no-merges',
    '--date=short',
    '--format=%h\x1f%ad\x1f%s\x1f%b\x1e',
    '--',
    '.',
  ]);

  return raw
    .split('\x1e')
    .map((record) => record.replace(/^\n/, ''))
    .filter((record) => record.trim() !== '')
    .map((record) => {
      const [hash, date, subject, body = ''] = record.split('\x1f');
      return { hash, date, body: body.trim(), ...parseSubject(subject) };
    });
}

/** The first paragraph of the body, as a one-line summary. */
function firstParagraph(body) {
  if (!body) return null;
  const paragraph = body
    .split(/\n\s*\n/)[0]
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line !== '' && !/^(Co-Authored-By|Claude-Session|Signed-off-by):/i.test(line))
    .join(' ')
    .trim();
  return paragraph === '' ? null : paragraph;
}

function render(commits) {
  const lines = [
    '# Changelog',
    '',
    '<!-- Generated by `npm run changelog` from git history. Do not edit by hand:',
    '     the next run overwrites it. Change a commit message instead. -->',
    '',
    'Every commit that touched this project, newest first. Grouped by the date',
    'it landed, and by [conventional commit](https://www.conventionalcommits.org)',
    'type within each date.',
    '',
    `${commits.length} commits.`,
    '',
  ];

  const byDate = new Map();
  for (const commit of commits) {
    if (!byDate.has(commit.date)) byDate.set(commit.date, []);
    byDate.get(commit.date).push(commit);
  }

  for (const [date, dayCommits] of byDate) {
    lines.push(`## ${date}`, '');

    for (const [type, label] of SECTIONS) {
      const matching = dayCommits.filter((commit) => commit.type === type);
      if (matching.length === 0) continue;

      lines.push(`### ${label}`, '');
      for (const commit of matching) {
        const breaking = commit.breaking ? '**Breaking.** ' : '';
        lines.push(`- ${breaking}${commit.description} (\`${commit.hash}\`)`);

        // The body is where the reasoning lives, and the reasoning is the part
        // worth keeping — the subject alone rarely says why.
        const summary = firstParagraph(commit.body);
        if (summary) lines.push(`  ${summary}`);
      }
      lines.push('');
    }
  }

  return `${lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
}

const commits = collectCommits();
if (commits.length === 0) {
  console.error('No commits found for this project. Is this a git checkout?');
  process.exit(1);
}

const output = render(commits);

if (process.argv.includes('--check')) {
  const current = existsSync(outputPath) ? readFileSync(outputPath, 'utf8') : '';
  if (current !== output) {
    console.error('CHANGELOG.md is out of date. Run: npm run changelog');
    process.exit(1);
  }
  console.log(`CHANGELOG.md is up to date (${commits.length} commits).`);
  process.exit(0);
}

writeFileSync(outputPath, output);
console.log(`Wrote CHANGELOG.md — ${commits.length} commits.`);
